### PR TITLE
Modify build-process to be able to use dfxml as system-wide installable shared library

### PR DESCRIPTION
**Pull request by jgru**
Dear Simson, 

this PR modifies the build-process and the include-statements of various source files to be able to use dfxml -- in addition to the current usage -- as a shared library installed on the system. Please see the examples, which I added to the README.md. 

I am asking for a thorough review to ensure, that these changes do not break something on MacOS, so please take your time.

Thank you already in advance for considering this PR for a merge. 

Best regards  
    Jan

### CODE REVIEW

**Comment by simsong** [comment]
Oh, we really don't like force-pushes. Let me see what you've done. I'm not sure why the GitHub Action didn't run for you.

**Comment by simsong** [comment]
I can't accept this PR. When you change the `#include` statements like this, it prevents me from testing the software _before_ it gets installed:

https://github.com/jgru/dfxml_cpp/blob/0a72ab6c15e127a9a544daca3e0c3deb35188eeb/src/testapp_catch2.cpp#L5

```
#include <dfxml_hash_t.h>
#include <dfxml_writer.h>
#include <dfxml_cpuid.h>
```

You included `<dfxml_config.h>`, which is a good idea, so I'm making that change for the test program.

I'm going to close this and request that you allow me to get this all working on both Ubuntu and MacOS. I'll look at what you have suggested and take things from it.

Simson

**Comment by jgru** [comment]
> Oh, we really don't like force-pushes. Let me see what you've done. I'm not sure why the GitHub Action didn't run for you.

Hm, usually this is no problem before the PR. 

> I can't accept this PR. When you change the `#include` statements like this, it prevents me from testing the software _before_ it gets installed:
> 
> https://github.com/jgru/dfxml_cpp/blob/0a72ab6c15e127a9a544daca3e0c3deb35188eeb/src/testapp_catch2.cpp#L5
> 

You can change the include headers in the test-program to `#include "dfxml_..."`, which should work also. (Automake takes good care of the necessary linking).

BTW on Debian the build and also `make check` runs fine, with this additions and without installing. 
(I just forgot to change `#include "hash_t.h"` in `dfxml_reader.h`, which should be `#include <dfxml_hash_t.h>`.)

> You included `<dfxml_config.h>`, which is a good idea, so I'm making that change for the test program.

Okay! I think those changes could be quite helpful in total. Since it is convenient to be able to use `-ldfxml`, when compiling a program depending on dfxml. 

>I'm going to close this and request that you allow me to get this all working on both Ubuntu and MacOS. I'll look at what you have suggested and take things from it.

Ok, please let me know, if I can do something. 

Best regards   
Jan

**Comment by jgru** [comment]
> Oh, we really don't like force-pushes. Let me see what you've done. I'm not sure why the GitHub Action didn't run for you.

I think, that the actions did not run, because there is no `pull_request` target. This is addressed in #3

**Comment by simsong** [comment]
Okay, I got it merged back to main. Please take a look and if there is more needed, please issue a new PR against Main. Thanks!

**Comment by jgru** [comment]
> Okay, I got it merged back to main. Please take a look and if there is more needed, please issue a new PR against Main. Thanks!


Great, thanks! I'll have a look!

**Pull request closed without merging**
