### PR TITLE
Remove Python code from C++ code base

### PR DESCRIPTION
**Pull request by ajnelson-nist**
@simsong , I think I caught everything the CI would run, but you should wait for CI to give a green checkmark before merging this one.

### CODE REVIEW

**Comment by ajnelson-nist** [comment]
If CI passes, it's good to me to merge.

**Comment by simsong** [comment]
Now we need to fix the CI

**Comment by ajnelson-nist** [comment]
Aye.  Good news / bad news: I don't think this is an error introduced from anything that happened today.  Bad news: I'm not sure how long it has been broken.

The first issue I see reported is `ltmain.sh` not being found:
https://github.com/dfxml-working-group/dfxml_cpp/pull/1/checks?check_run_id=2975612957#step:6:19

Seems that file never existed in the Git history, and I forget if libtool is supposed to build it.

I'm not in a good spot, timing-wise, to fix this today, and I'm about to be off for the weekend.  May I leave this with you, @simsong ?

**Comment by simsong** [comment]
Will fix it


----
Sent from my phone.

On Jul 2, 2021, at 4:33 PM, Alex Nelson ***@***.***> wrote:

﻿
Aye. Good news / bad news: I don't think this is an error introduced from anything that happened today. Bad news: I'm not sure how long it has been broken.

The first issue I see reported is ltmain.sh not being found:
https://github.com/dfxml-working-group/dfxml_cpp/pull/1/checks?check_run_id=2975612957#step:6:19

Seems that file never existed in the Git history, and I forget if libtool is supposed to build it.

I'm not in a good spot, timing-wise, to fix this today, and I'm about to be off for the weekend. May I leave this with you, @simsong ?

**Comment by simsong** [comment]
Getting closer. Will fix this later today

**Comment by simsong** [comment]
finally. Now need to get codecov working.

**Pull request merged**
